package com.crackedgames.craftics.combat;

import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;

/**
 * The symbol and color shown for every Craftics status effect.
 *
 * <p>Effects reach the client as NAMES inside the combat sync string, and those names come
 * from two separate systems that never shared a vocabulary: player effects are
 * {@link CombatEffects.EffectType} (which sends {@code displayName}, e.g. "Regeneration") and
 * enemy effects are flat fields on {@link CombatEntity} (which send past-tense verbs, e.g.
 * "Regenerating"). Addons contribute a third set through {@code CustomEffectDef}. This table
 * is the one place those vocabularies are reconciled, so a poisoned player and a poisoned
 * skeleton show the same icon.
 *
 * <p>Lookup is by name, case-insensitively, and it tolerates the trailing detail the sync
 * appends - {@code "Poisoned(3t)"}, {@code "Weakened(-2ATK,3t)"} and {@code "Poison"} all
 * resolve to the same icon. Anything unrecognized (a new addon effect) falls back to a
 * neutral marker rather than vanishing, so an unknown effect is still visibly SOMETHING.
 *
 * <p>Kept in the common source set (not client-only) and free of Minecraft imports so the
 * mapping can be unit-tested without a Minecraft bootstrap.
 */
public final class EffectIcons {

    private EffectIcons() {}

    /**
     * One effect's presentation: an 8x8 sprite drawn above the afflicted entity's head.
     *
     * <p>{@code texture} is the sprite's base name, resolving to
     * {@code assets/craftics/textures/gui/effects/<texture>.png}. The sprites are drawn in
     * full color, so {@code color} is NOT a tint - it is the effect's identifying color, kept
     * for the HUD chips and as the value the sprite generator paints with.
     *
     * @param texture base name of the 8x8 sprite (no path, no .png)
     * @param color   0xRRGGBB identifying color
     * @param harmful true for debuffs; lets callers filter buffs from debuffs
     */
    public record Icon(String texture, int color, boolean harmful) {}

    /** Shown for an effect with no entry - an unknown/addon effect is still visible. */
    public static final Icon UNKNOWN = new Icon("unknown", 0xFFFFFF, false);

    // Colors chosen to read at a glance and to stay distinct from each other at icon size.
    private static final int RED        = 0xFF5555;
    private static final int DARK_RED   = 0xAA0000;
    private static final int ORANGE     = 0xFF8800;
    private static final int YELLOW     = 0xFFDD44;
    private static final int GREEN      = 0x55FF55;
    private static final int DARK_GREEN = 0x228822;
    private static final int AQUA       = 0x55FFFF;
    private static final int BLUE       = 0x5599FF;
    private static final int PURPLE     = 0xAA55FF;
    private static final int PINK       = 0xFF77CC;
    private static final int GRAY       = 0xAAAAAA;
    private static final int DARK_GRAY  = 0x555555;
    private static final int WHITE      = 0xFFFFFF;
    private static final int BLACK      = 0x222222;
    private static final int BROWN      = 0xAA7744;

    /**
     * Canonical name -> icon. Every key is lowercase; {@link #forName} lowercases its input.
     * Both vocabularies (player {@code displayName} and enemy sync verb) map to the same
     * Icon, which is the whole point of this table.
     */
    private static final Map<String, Icon> ICONS = new LinkedHashMap<>();

    private static void put(Icon icon, String... names) {
        for (String n : names) ICONS.put(n.toLowerCase(Locale.ROOT), icon);
    }

    // Each effect gets its own hand-shaped 16x16 sprite under
    // assets/craftics/textures/gui/effects/. Sprites (rather than font glyphs) are what make
    // these icons possible at all: Minecraft's default font covers only a slice of Unicode, and
    // a character the font lacks draws as NOTHING while still reporting no width - so an
    // icon-by-glyph scheme fails silently and invisibly for most interesting symbols.
    //
    // The sprite for each name below is generated by tools/generate_effect_icons.py, which is
    // the source of truth for the artwork. Re-run it after adding an entry here.
    static {
        // ---- Buffs ----
        put(new Icon("regeneration", GREEN, false),  "regeneration", "regenerating");
        put(new Icon("strength", RED, false),        "strength", "strengthened");
        put(new Icon("resistance", BLUE, false),     "resistance", "resistant");
        put(new Icon("speed", AQUA, false),          "speed");
        put(new Icon("haste", YELLOW, false),        "haste", "hastened");
        put(new Icon("absorption", YELLOW, false),   "absorption");
        put(new Icon("luck", GREEN, false),          "luck");
        put(new Icon("slow_falling", WHITE, false),  "slow_falling", "slow falling", "slowfalling");
        put(new Icon("fire_resistance", ORANGE, false), "fire_resistance", "fire resistance");
        put(new Icon("invisibility", GRAY, false),   "invisibility");
        put(new Icon("water_breathing", AQUA, false), "water_breathing", "water breathing");
        put(new Icon("airtime", AQUA, false),        "airtime");

        // ---- Debuffs ----
        put(new Icon("poison", DARK_GREEN, true),    "poison", "poisoned");
        put(new Icon("wither", BLACK, true),         "wither", "withered");
        put(new Icon("burning", ORANGE, true),       "burning", "burn");
        put(new Icon("bleeding", DARK_RED, true),    "bleeding", "bleed");
        put(new Icon("slowness", BROWN, true),       "slowness", "slowed");
        put(new Icon("weakness", GRAY, true),        "weakness", "weakened");
        put(new Icon("blindness", DARK_GRAY, true),  "blindness", "blinded");
        put(new Icon("mining_fatigue", DARK_GRAY, true), "mining_fatigue", "mining fatigue");
        put(new Icon("levitation", PURPLE, true),    "levitation");
        put(new Icon("darkness", BLACK, true),       "darkness");
        put(new Icon("soaked", BLUE, true),          "soaked");
        put(new Icon("confusion", PINK, true),       "confusion", "confused");
        put(new Icon("warped", PURPLE, true),        "warped");

        // ---- Enemy-only states (no player equivalent) ----
        put(new Icon("stunned", YELLOW, true),       "stunned");
        put(new Icon("enraged", RED, false),         "enraged");
        put(new Icon("marked", RED, true),           "marked");
        put(new Icon("frozen", AQUA, true),          "frozen");
        put(new Icon("taunting", ORANGE, false),     "taunting");
        put(new Icon("exposed", PURPLE, true),       "exposed");
    }

    /**
     * The icon for an effect name as it appears on the wire.
     *
     * <p>Strips any trailing parenthetical detail, so {@code "Weakened(-2ATK,3t)"} resolves
     * the same as {@code "Weakened"}. Never returns null: an unrecognized name (typically a
     * new addon effect) yields {@link #UNKNOWN} so it still renders.
     */
    public static Icon forName(String rawName) {
        String key = baseName(rawName);
        if (key.isEmpty()) return UNKNOWN;
        Icon icon = ICONS.get(key);
        return icon != null ? icon : UNKNOWN;
    }

    /** True if this effect name has a real entry (i.e. is not falling back to UNKNOWN). */
    public static boolean isKnown(String rawName) {
        return ICONS.containsKey(baseName(rawName));
    }

    /**
     * The lookup key for a wire name: lowercased, with any {@code "(...)"} duration/magnitude
     * suffix and any roman-numeral level removed. {@code "Poisoned(3t)"} -> {@code "poisoned"},
     * {@code "Regeneration II"} -> {@code "regeneration"}.
     */
    public static String baseName(String rawName) {
        if (rawName == null) return "";
        String s = rawName.trim();
        int paren = s.indexOf('(');
        if (paren >= 0) s = s.substring(0, paren);
        s = s.trim();
        // Drop a trailing roman-numeral level ("Strength II" -> "Strength").
        int lastSpace = s.lastIndexOf(' ');
        if (lastSpace > 0 && isRoman(s.substring(lastSpace + 1))) {
            s = s.substring(0, lastSpace);
        }
        return s.trim().toLowerCase(Locale.ROOT);
    }

    private static boolean isRoman(String s) {
        if (s.isEmpty()) return false;
        for (int i = 0; i < s.length(); i++) {
            if ("IVXivx".indexOf(s.charAt(i)) < 0) return false;
        }
        return true;
    }

    /**
     * Metadata tags that share the enemy sync blob with the effect names. Anything in the
     * blob that is NOT one of these is an effect - the same rule the HUD already uses.
     */
    private static final String[] META_PREFIXES = {
        "boss=", "name=", "atk=", "def=", "spd=", "range=", "ench=", "mv=", "phase="
    };

    /**
     * Pull the status-effect names out of an enemy's sync blob
     * ({@code "zombie;name=Bob;atk=5;Poisoned(3t);Burning(2t)"} -> {@code [Poisoned(3t),
     * Burning(2t)]}).
     *
     * <p>The blob mixes effects with {@code key=value} metadata and a bare {@code ally} tag,
     * and the first segment is the entity type id. Effects are whatever's left over.
     */
    public static java.util.List<String> parseEnemyEffects(String blob) {
        java.util.List<String> out = new java.util.ArrayList<>();
        if (blob == null || blob.isEmpty()) return out;
        String[] parts = blob.split(";");
        // parts[0] is the entity type id, never an effect.
        outer:
        for (int i = 1; i < parts.length; i++) {
            String p = parts[i];
            if (p.isEmpty() || p.equals("ally")) continue;
            for (String meta : META_PREFIXES) {
                if (p.startsWith(meta)) continue outer;
            }
            out.add(p);
        }
        return out;
    }

    /**
     * Pull the effect names out of a PLAYER effect string, which uses a different format
     * again: {@code CombatEffects.getDisplayString()} joins with {@code " | "} and appends
     * {@code "(3t)"} durations, e.g. {@code "Poison (2t) | Strength II (5t)"}.
     *
     * <p>The "Hidden" stealth marker is injected into this string by the server and is a HUD
     * indicator rather than a real effect, so it is skipped.
     */
    public static java.util.List<String> parsePlayerEffects(String display) {
        java.util.List<String> out = new java.util.ArrayList<>();
        if (display == null || display.isEmpty()) return out;
        for (String part : display.split("\\|")) {
            String s = part.trim();
            if (s.isEmpty()) continue;
            if (baseName(s).equals("hidden")) continue;
            out.add(s);
        }
        return out;
    }

    /** True if this effect should emit ambient particles around the afflicted entity. */
    public static boolean hasParticles(String rawName) {
        return PARTICLE_EFFECTS.contains(baseName(rawName));
    }

    /**
     * Effects that emit ambient particles. Deliberately limited to the ones with an obvious
     * physical read (fire, venom, water, decay, blood, ice, fury) - giving EVERY effect a
     * particle would bury the arena in them and cost framerate on low-end machines for no
     * added clarity.
     */
    private static final java.util.Set<String> PARTICLE_EFFECTS = java.util.Set.of(
        "burning", "burn",
        "poison", "poisoned",
        "wither", "withered",
        "bleeding", "bleed",
        "soaked",
        "frozen",
        "enraged",
        "regeneration", "regenerating");
}
