package com.crackedgames.craftics.client;

import com.crackedgames.craftics.combat.EffectIcons;
import net.fabricmc.fabric.api.client.rendering.v1.WorldRenderContext;
import net.fabricmc.fabric.api.client.rendering.v1.WorldRenderEvents;
import net.minecraft.client.MinecraftClient;
import net.minecraft.client.render.Camera;
import net.minecraft.client.render.RenderLayer;
import net.minecraft.client.render.VertexConsumer;
import net.minecraft.client.render.VertexConsumerProvider;
import net.minecraft.client.util.math.MatrixStack;
import net.minecraft.entity.Entity;
import net.minecraft.entity.player.PlayerEntity;
import net.minecraft.util.Identifier;
import net.minecraft.util.math.Vec3d;
import org.joml.Matrix4f;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * Floating status-effect icons above every combatant's head - players, allies and enemies.
 *
 * <p>One 8x8 sprite per active effect, laid out in a horizontal row centered on the entity and
 * billboarded to face the camera. They persist for exactly as long as the effect does, because
 * they are drawn straight from the synced combat state rather than from any timer of their
 * own: when the server stops sending the effect, the icon stops drawing.
 *
 * <p>Sprites, not font glyphs. An earlier version drew Unicode symbols through the text
 * renderer and nothing appeared in game: Minecraft's default font covers only a slice of
 * Unicode, and a character it lacks draws as nothing while still reporting no width, so the
 * icons failed silently and invisibly. The artwork now lives in
 * {@code assets/craftics/textures/gui/effects/} (generated by
 * {@code tools/generate_effect_icons.py}), which sidesteps the font entirely.
 *
 * @since 0.3.0
 */
public final class EffectIconRenderer {

    private EffectIconRenderer() {}

    /** Height above the entity's own height to float the icon row. */
    private static final double HEIGHT_OFFSET = 0.75;

    /** Side length of one icon in world units. */
    private static final float ICON_SIZE = 0.28f;

    /** Gap between adjacent icons, in world units. */
    private static final float ICON_GAP = 0.06f;

    /** Don't draw icons for combatants further away than this (squared). */
    private static final double MAX_DIST_SQ = 48 * 48;

    /** Full-bright, so an icon reads the same in a dark cave as in daylight. */
    private static final int FULL_BRIGHT = 0xF000F0;

    /** Cached texture Identifiers, so we don't rebuild one per icon per frame. */
    private static final Map<String, Identifier> TEXTURES = new HashMap<>();

    private static Identifier textureFor(String name) {
        return TEXTURES.computeIfAbsent(name,
            n -> Identifier.of("craftics", "textures/gui/effects/" + n + ".png"));
    }

    /** Register the world-render callback. Called once from client init. */
    public static void register() {
        WorldRenderEvents.AFTER_ENTITIES.register(EffectIconRenderer::onRenderWorld);
    }

    private static void onRenderWorld(WorldRenderContext ctx) {
        MinecraftClient client = MinecraftClient.getInstance();
        if (client.world == null || client.options.hudHidden) return;
        if (!CombatState.isInCombat()) return;

        MatrixStack matrices = ctx.matrixStack();
        VertexConsumerProvider consumers = ctx.consumers();
        if (matrices == null || consumers == null) return;

        Camera camera = ctx.camera();
        Vec3d cam = camera.getPos();
        //? if <=1.21.4 {
        float tickDelta = ctx.tickCounter().getTickDelta(false);
        //?} else {
        /*float tickDelta = ctx.tickCounter().getTickProgress(false);
        *///?}

        var enemyTypes = CombatState.getEnemyTypeMap();
        var allyTypes = CombatState.getAllyTypeMap();

        for (Entity entity : client.world.getEntities()) {
            Vec3d pos = entity.getLerpedPos(tickDelta);
            if (pos.squaredDistanceTo(cam) > MAX_DIST_SQ) continue;

            List<String> effects = effectsFor(entity, enemyTypes, allyTypes);
            if (effects.isEmpty()) continue;

            drawIconRow(matrices, consumers, camera, cam, entity, pos, effects);
        }
    }

    /**
     * The active effects on {@code entity}, or an empty list if it isn't a tracked combatant.
     *
     * <p>Three sources, because effects reach the client three different ways: enemies and
     * allies by entity id in the combat sync's type blob, and players by UUID in the party
     * list (falling back to the scalar effects string in solo play, where no party list is
     * sent).
     */
    private static List<String> effectsFor(Entity entity,
                                           Map<Integer, String> enemyTypes,
                                           Map<Integer, String> allyTypes) {
        if (entity instanceof PlayerEntity player) {
            return EffectIcons.parsePlayerEffects(playerEffectString(player));
        }
        String blob = enemyTypes.get(entity.getId());
        if (blob == null) blob = allyTypes.get(entity.getId());
        if (blob == null) return List.of();
        return EffectIcons.parseEnemyEffects(blob);
    }

    /**
     * A player's effect string. In multiplayer each member's own effects arrive in the party
     * list keyed by UUID; in solo play the party list is empty and the scalar string is the
     * local player's own.
     */
    private static String playerEffectString(PlayerEntity player) {
        UUID uuid = player.getUuid();
        for (CombatState.PartyMemberHp member : CombatState.getPartyHpList()) {
            if (uuid.toString().equals(member.uuid())) {
                return member.dead() ? "" : member.effects();
            }
        }
        MinecraftClient client = MinecraftClient.getInstance();
        boolean isLocal = client.player != null && client.player.getUuid().equals(uuid);
        return isLocal ? CombatState.getPlayerEffects() : "";
    }

    /** Draw the effects as one horizontal, camera-facing row centered over the entity. */
    private static void drawIconRow(MatrixStack matrices, VertexConsumerProvider consumers,
                                    Camera camera, Vec3d cam, Entity entity, Vec3d pos,
                                    List<String> effects) {
        int count = effects.size();
        float totalWidth = count * ICON_SIZE + (count - 1) * ICON_GAP;

        matrices.push();
        matrices.translate(
            pos.x - cam.x,
            pos.y - cam.y + entity.getHeight() + HEIGHT_OFFSET,
            pos.z - cam.z);
        // Billboard: face the camera, exactly as the party label does.
        matrices.multiply(camera.getRotation());
        // 180° in-plane flip - the sign of the negative X/Y scale every vanilla-style label
        // applies after the camera rotation (the party label's scale(-0.025, -0.025, ...)).
        // The raw billboard space has +Y screen-up / +X screen-left relative to the UV
        // convention in drawSprite, so without this the sprites drew upside down and mirrored.
        matrices.scale(-1.0f, -1.0f, 1.0f);

        Matrix4f matrix = matrices.peek().getPositionMatrix();

        // Row is centered on the entity: start half a row-width to the left.
        float x = -totalWidth / 2.0f;
        for (String effect : effects) {
            EffectIcons.Icon icon = EffectIcons.forName(effect);
            drawSprite(consumers, matrix, textureFor(icon.texture()), x, ICON_SIZE);
            x += ICON_SIZE + ICON_GAP;
        }
        matrices.pop();
    }

    /**
     * One textured quad in the billboarded local space, its left edge at {@code x}.
     *
     * <p>Assumes the caller has applied the 180° in-plane flip (the negative X/Y scale in
     * {@link #drawIconRow}); in that space +Y is screen-down and v=1 is the sprite's bottom
     * edge, matching the UVs below.
     */
    private static void drawSprite(VertexConsumerProvider consumers, Matrix4f matrix,
                                   Identifier texture, float x, float size) {
        // getTextSeeThrough gives a textured, alpha-blended layer that draws through geometry,
        // so an icon stays visible when its owner is behind cover - the point of the feature.
        VertexConsumer vc = consumers.getBuffer(RenderLayer.getTextSeeThrough(texture));

        float x0 = x;
        float x1 = x + size;
        float y0 = -size / 2.0f;
        float y1 = size / 2.0f;

        // Emit BOTH windings so the sprite is double-sided. The see-through text layer culls
        // back faces, and after the camera-facing billboard a single winding can end up facing
        // AWAY from the camera - which culled the whole quad and drew nothing (the reason the
        // icons were invisible in game while the text-based party label, whose glyph quads are
        // wound correctly by the font renderer, showed fine). Drawing front and back removes the
        // dependency on getting the winding exactly right for this layer's cull mode.
        //
        // U is FLIPPED (x0->1, x1->0) to cancel the horizontal mirror introduced by the
        // drawIconRow scale(-1, -1, 1). Without this, chiral icons (e.g. the confusion "?")
        // rendered mirror-imaged / facing the wrong way. The -1 X scale mirrors geometry;
        // pre-mirroring the texture in UV space restores the correct handedness.
        // Front face.
        vc.vertex(matrix, x0, y1, 0).color(255, 255, 255, 255).texture(1f, 1f).light(FULL_BRIGHT);
        vc.vertex(matrix, x1, y1, 0).color(255, 255, 255, 255).texture(0f, 1f).light(FULL_BRIGHT);
        vc.vertex(matrix, x1, y0, 0).color(255, 255, 255, 255).texture(0f, 0f).light(FULL_BRIGHT);
        vc.vertex(matrix, x0, y0, 0).color(255, 255, 255, 255).texture(1f, 0f).light(FULL_BRIGHT);
        // Back face (reversed winding).
        vc.vertex(matrix, x0, y0, 0).color(255, 255, 255, 255).texture(1f, 0f).light(FULL_BRIGHT);
        vc.vertex(matrix, x1, y0, 0).color(255, 255, 255, 255).texture(0f, 0f).light(FULL_BRIGHT);
        vc.vertex(matrix, x1, y1, 0).color(255, 255, 255, 255).texture(0f, 1f).light(FULL_BRIGHT);
        vc.vertex(matrix, x0, y1, 0).color(255, 255, 255, 255).texture(1f, 1f).light(FULL_BRIGHT);
    }
}
