package com.crackedgames.craftics.api.registry;

import com.crackedgames.craftics.CrafticsMod;
import com.crackedgames.craftics.api.RegistrationSource;
import org.jetbrains.annotations.Nullable;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Registry of between-level events, stored in insertion order.
 *
 * <p>After each level Craftics calls {@link #roll} to select an event based on
 * cumulative probability. Built-in events are registered by {@code VanillaContent};
 * addons add their own through {@code CrafticsAPI.registerEvent}.
 *
 * @since 0.2.0
 */
public final class EventRegistry {
    private static final List<EventEntry> EVENTS = new ArrayList<>();
    /** Events loaded from JSON datapacks — dropped on /reload. */
    private static final Set<EventEntry> DATAPACK_EVENTS = new HashSet<>();

    private EventRegistry() {}

    /** Register an event from code (survives {@code /reload}). */
    public static void register(EventEntry entry) {
        register(entry, RegistrationSource.CODE);
    }

    /** Register an event, tagging whether it came from code or a datapack. */
    public static void register(EventEntry entry, RegistrationSource source) {
        EVENTS.add(entry);
        if (source == RegistrationSource.DATAPACK) {
            DATAPACK_EVENTS.add(entry);
        }
    }

    /** Remove every event that was loaded from a JSON datapack. */
    public static void clearDatapackEntries() {
        EVENTS.removeAll(DATAPACK_EVENTS);
        DATAPACK_EVENTS.clear();
    }

    /**
     * Select an event id by walking the cumulative-probability cascade.
     *
     * @param eventRoll    a random float in {@code [0, 1)} generated by {@code CombatManager}
     * @param biomeOrdinal the current biome's ordinal; events whose
     *                     {@link EventEntry#minBiomeOrdinal()} exceeds this value are skipped
     * @return the id of the selected event, or {@code "none"} if no event triggers
     */
    public static String roll(float eventRoll, int biomeOrdinal) {
        // Collect eligible events
        List<EventEntry> eligible = new ArrayList<>();
        float totalProb = 0;
        for (EventEntry e : EVENTS) {
            if (biomeOrdinal >= e.minBiomeOrdinal()) {
                eligible.add(e);
                totalProb += e.probability();
            }
        }

        // Overflow protection
        float scale = 1.0f;
        if (totalProb > 0.90f) {
            CrafticsMod.LOGGER.warn("Event probability overflow: total={}, scaling down", totalProb);
            scale = 0.90f / totalProb;
        }

        // Roll through cascade
        float cumulative = 0;
        for (EventEntry e : eligible) {
            cumulative += e.probability() * scale;
            if (eventRoll < cumulative) {
                return e.id();
            }
        }
        return "none";
    }

    /** The event registered under {@code id}, or {@code null} if none matches. */
    @Nullable
    public static EventEntry getById(String id) {
        for (EventEntry e : EVENTS) {
            if (e.id().equals(id)) return e;
        }
        return null;
    }

    /** Every registered event as an immutable snapshot. */
    public static List<EventEntry> getAll() {
        return List.copyOf(EVENTS);
    }
}
